export const types = {
    GET_SHOPPING_CART: "GET_SHOPPING_CART",
    CLEAR_CART: "CLEAR_CART",
    START_LOADING: "START_LOADING",
    ADD_TO_CART: "ADD_TO_CART",
    INC_QUANTITY: "INC_QUANTITY",
    DEC_QUANTITY: "DEC_QUANTITY"
};