export const types = {
    GET_NOTIFICATION_LIST: "GET_NOTIFICATION_LIST",
    GET_MORE_NOTIFICATIONS: "GET_MORE_NOTIFICATIONS",
    SET_NOTIFICATION_READ: "SET_NOTIFICATION_READ",
    SET_NOTIFICATION_READ_COUNT: "SET_NOTIFICATION_READ_COUNT",
    CLEAR_NOTIFICATION_READ: "CLEAR_NOTIFICATION_READ",
};