export const CLEAR_REDUCERS = 'CLEAR_REDUCERS';


export const GET_CURRENT_USER= "GET_CURRENT_USER";
export const SET_CURRENT_USER= "SET_CURRENT_USER";



export const GET_ALL_CATEGORIES_STARTED = "GET_ALL_CATEGORIES_STARTED";
export const GET_ALL_CATEGORIES_SUCCEEDED = "GET_ALL_CATEGORIES_SUCCEEDED";
export const CLEAR_CATEGORIES = "CLEAR_CATEGORIES";



export const GET_ALL_PRODUCTS_STARTED = "GET_ALL_PRODUCTS_STARTED"
export const GET_ALL_PRODUCTS_SUCCEEDED = "GET_ALL_PRODUCTS_SUCCEEDED"



export const GET_SHOPPING_CART =  "GET_SHOPPING_CART";
export const CLEAR_CART =  "CLEAR_CART";
export const  START_LOADING =  "START_LOADING";
export const  ADD_TO_CART =  "ADD_TO_CART";
export const  INC_QUANTITY = "INC_QUANTITY";
export const  DEC_QUANTITY = "DEC_QUANTITY";


export const OFFLINE_CONNECTION= "OFFLINE_CONNECTION";

export const GET_ADS_SLIDER= "GET_ADS_SLIDER";

export const GET_NOTIFICATION_LIST= "GET_NOTIFICATION_LIST";
export const GET_MORE_NOTIFICATIONS= "GET_MORE_NOTIFICATIONS";
export const SET_NOTIFICATION_READ= "SET_NOTIFICATION_READ";
export const SET_NOTIFICATION_READ_COUNT= "SET_NOTIFICATION_READ_COUNT";
export const CLEAR_NOTIFICATION_READ= "CLEAR_NOTIFICATION_READ";

export const GET_ALL_PRODUCTS= "GET_ALL_PRODUCTS"

export const LOGOUT= "LOGOUT";